export const GET_GEOCODE_REQUESTED = 'GET_GEOCODE_REQUESTED';
export const GET_GEOCODE_SUCCESS = 'GET_GEOCODE_SUCCESS';
export const GET_GEOCODE_FAILED = 'GET_GEOCODE_FAILED';
export const GET_GEOCODE = 'GET_GEOCODE';

export const GET_INFO_REQUESTED = 'GET_INFO_REQUESTED';
export const GET_INFO_SUCCESS = 'GET_INFO_SUCCESS';
export const GET_INFO_FAILED = 'GET_INFO_FAILED';

export const GET_LOCATION_REQUESTED =  'GET_LOCATION_REQUESTED';
export const GET_LOCATION_SUCCESS = 'GET_LOCATION_SUCCESS';
export const GET_LOCATION_FAILED = 'GET_LOCATION_FAILED';
